version: '3'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "8080:80"
      - "8000:8000"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/testly.conf

  backend:
    build:
      context: ./backend
    image: "testly-backend:${BUILD_NUM:-development}"
    command: gunicorn testly.wsgi -c /code/config/gunicorn.py
    depends_on:
      - db
      - redis
    environment:
     - REDIS_URL=tcp://redis:6379
    links:
      - redis:redis
    volumes:
      - ./config/gunicorn.py:/code/config/gunicorn.py

  worker:
    image: "testly-backend:${BUILD_NUM:-development}"
    command: python manage.py rqworker testly-default
    environment:
     - REDIS_URL=tcp://redis:6379
    depends_on:
      - db
      - redis
    links:
      - redis:redis

  db:
    image: postgres:9.5
    environment:
     - POSTGRES_USER=testly_client
     - POSTGRES_PASSWORD=testly
     - POSTGRES_DB=testly

  redis:
    image: redis:latest
