version: '3'
services:
  frontend:
    build:
      context: ./frontend
    image: "${REPO:-mochawich}/testly-frontend:${BUILD_NUM:-development}"
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    image: "${REPO:-mochawich}/testly-backend:${BUILD_NUM:-development}"
    depends_on:
      - db
      - redis
    environment:
     - REDIS_URL=tcp://redis:6379
    links:
      - redis:redis
    ports:
      - "8000:8000"

  worker:
    image: "${REPO:-mochawich}/testly-backend:${BUILD_NUM:-development}"
    command: python manage.py rqworker testly-default
    environment:
     - REDIS_URL=tcp://redis:6379
    depends_on:
      - db
      - redis
    links:
      - redis:redis

  db:
    image: postgres:9.5
    environment:
     - POSTGRES_USER=testly_client
     - POSTGRES_PASSWORD=testly
     - POSTGRES_DB=testly

  redis:
    image: redis:latest
