apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.10.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - env:
        - name: TY_DB_HOST
          value: shoutitprod.cv68lwjxpbj3.eu-west-1.rds.amazonaws.com
        - name: REDIS_URL
          value: tcp://redis:6379
        image: mochawich/testly-backend:1.0.1
        name: backend
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
